### ISSUE TITLE
NDI Options

### ISSUE THREAD

**Issue by 24se7en** [Cuperino/QPrompt-Teleprompter#232] opened 2023-11-10 10:03 UTC
It would be great for our business to use professional NDI option for our autocue monitors in Events, hopely you can work on it

**Comment by Cuperino** [comment] 2023-11-10 12:46
It's in our plans. I need to figure out a way to grab the picture without degrading performance first, but this is something the project will have at some point.

**Comment by Cuperino** [comment] 2023-11-10 12:47
Duplicate of #41

**Closed by Cuperino** 2023-11-10 12:46 UTC
