### ISSUE TITLE
On Android screen fades and energy saver kicks in

### ISSUE THREAD

**Issue by tsvetko24** [Cuperino/QPrompt-Teleprompter#307] opened 2024-12-07 00:48 UTC
**Are you ready to report?**

Yep

**Bug Description**

On my Android device, while the prompt is going the screen fades away and eventually goes black as the prompts progress.
I need app to have permissions to keep the phone with Always On screen, while the prompt is rolling. 

**Steps to Reproduce**
1. Install the app for Android.
2. Move the device in landscape mode
3. Load HTML file with some prompt longer than a minute
4. Sleep screen kicks in and the display fades

**Expected behavior**

While roll the prompts the screen is active

**Detailed description of display configuration** (if applicable)

As workaround user can go to Settings -> Display -> and change the waiting time to 10 minutes for instance, but after finish using the phone as Teleprompter device, the user need to remember to get it back to 30 sec.

**Screenshots** (optional)

Not an option, when try to screenshot, it wakes up. However I can take a picture from another phone how it sleeps while rolls the prompts.

**Device information**
 - QPrompt Version: 1.1.2 (main/072f0a7)
 - Operating System: ANDROID 

**Additional context**

Mid Priority

**Comment by Cuperino** [comment] 2024-12-08 15:47
Thanks for reporting. This is a duplicate of issue #78, so we'll keep track of this over there. I'll copy your issue description since you've done a better job than I at writing one. That is helpful.

**Closed by Cuperino** 2024-12-08 15:47 UTC
Labels: duplicate
