### ISSUE TITLE
Cursor focus moves when switching between normal and small fonts

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt-Teleprompter#245] opened 2024-03-03 02:14 UTC
**Bug Description**
When cycling between normal and small font sizes, unless beginning of paragraph coincides with the middle of the prompt window, cursor position moves.
Also appears to occur when paragraph spacing is >000%

**Steps to Reproduce**
1. Load attached long test file
2. Pick a paragraph, center the beginning in the middle of a full-screen QPrompt window, and place the cursor at the beginning.
3. Cycle between the normal and AA font sizes, cursor should remain where it was placed.
4.  In the normal size, slightly scroll the script so the selected paragraph is either lower or higher than the center.
5.  Repeat the cycling. Cursor should reposition at another place in the script.
6. Place cursor at the beginning of a paragraph, adjust paragraph spacing, cursor moves.

**Expected behavior**
Cursor should always position where is was placed regardless of script position

![screen](https://github.com/Cuperino/QPrompt-Teleprompter/assets/88691671/8fe7eaad-7da0-433e-bdea-deb3992fa5b1)

[test.html.zip](https://github.com/Cuperino/QPrompt-Teleprompter/files/14471423/test.html.zip)

**Device information**
 - Operating System: Debian Bookworm, latest updates

**Comment by Cuperino** [comment] 2024-03-03 06:04
Appears to be a duplicate of: https://github.com/Cuperino/QPrompt-Teleprompter/issues/223

**Comment by videosmith** [comment] 2024-03-03 13:53
My apologies. I did document more of why it happens due to vertical text positioning here.
    On Sunday, March 3, 2024 at 01:04:42 AM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Appears to be a duplicate of: #223

**Closed** 2024-03-03 19:25 UTC
Labels: duplicate
